image: node:latest
cache:
  paths:
    - node_modules/
pages:
  stage: deploy
  script:
     - npm i
     - npm run postinstall
     - npm run build
  artifacts:
    paths:
      - public
  only:
    - master
